[platformio]
default_envs = cam

[env:cam]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.arduino.memory_type = dio_opi
board_build.flash_mode = dio
board_build.f_flash = 80000000L
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DATOMS3R_CAM_GROVE_CHILD
    -DATOMS3R_CAM_CHILD_I2C_SDA=38
    -DATOMS3R_CAM_CHILD_I2C_SCL=39
lib_deps =
    bblanchon/ArduinoJson
    espressif/esp32-camera
